# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Java CI with Maven using Jfrog Artifactory

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    env: # define env vars for Maven here
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest

      - name: Configure JFrog CLI
        run: |
          jf c add soleng \
            --url=https://soleng.jfrog.io \
            --user=$ARTIFACTORY_USER \
            --password=$ARTIFACTORY_PASS \
            --interactive=false

      - name: Build with Maven via JFrog CLI
        run: jf mvn -B clean verify

      # - name: Build with Maven Wrapper
      #   run: ./mvnw -B verify

      - name: Log in to JFrog Docker
        run: echo "${{ secrets.ARTIFACTORY_PASS }}" | docker login soleng.jfrog.io -u ${{ secrets.ARTIFACTORY_USER }} --password-stdin

      - name: Build Docker image
        run: docker build -t soleng.jfrog.io/brianchu-docker-virtual/spring-petclinic:1.0.${{ github.run_number }} .

      - name: Push Docker image
        run: docker push soleng.jfrog.io/brianchu-docker-virtual/spring-petclinic:1.0.${{ github.run_number }}

      - name: Publish build info to Artifactory
        run: jf rt build-publish
